server:
  port: 9001
spring:
  application:
    name: service01
  datasource:
    username: root
    password: zjk688889
    url: jdbc:mysql://localhost:3306/tt?serverTimezone=UTC
  cloud:
    zookeeper:
      connect-string: 192.168.64.110:2181

