server:
  port: 8888
spring:
  datasource:
    username: root
    password: zjk688889
    url: jdbc:mysql://localhost:3306/tt?serverTimezone=UTC
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.zaxxer.hikari.HikariDataSource
  csrf: cb8299aa-9fd9-42da-a736-867c2f50cda2
mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.example.demo.Entity
logging:
  level:
     com.example.demo.scanmappers: debug