server:
  port: 9004
spring:
  application:
    name: service04
  datasource:
    username: root
    password: zjk688889
    url: jdbc:mysql://localhost:3306/tt?serverTimezone=UTC
  cloud:
    zookeeper:
      connect-string: 192.168.64.110:2181
feign:
  client:
    config:
       default:
          connectTimeout: 5000
          readTimeout: 1000
          loggerLevel: full #开启日志功能
  hystrix:
    enabled: true
logging:
  level:
     zhang.consumpy02.openfeign: debug  #前面的是接口所在的包...开启日志功能

