server:
  port: 8800
spring:
  application:
    name: service-8800
  datasource:
    username: root
    password: zjk688889
    url: jdbc:mysql://localhost:3306/tt?serverTimezone=UTC
  messages:
    basename: il8n.messages
