server:
  port: 9888
spring:
  application:
    name: getway9888
  datasource:
    username: root
    password: zjk688889
    url: jdbc:mysql://localhost:3306/tt?serverTimezone=UTC
  cloud:
    zookeeper:
      connect-string: 192.168.64.110:2181
    gateway:
      routes:
         - id: getway-9527
           uri: lb://getway9527
           predicates:
              - Path=/name/{id}
              - After=2021-02-24T14:10:03.778+08:00[Asia/Shanghai]
              - Header=zhang, getway9888


         - id: getway-9888
           uri: https://www.baidu.com
           predicates:
              - Path=/**